### ISSUE TITLE
Is container starting correctly?

### ISSUE THREAD

**Issue by snayakie** [chef-boneyard/chef-init#11]
Hi,

This probably is not an issue, just want to verify. When I run an image built by the "knife container build...." , the cookbooks used were 'recipe[apt],recipe[apache2]', the container start logs display the following, and stays there:
###### 
# Welcome to Chef Container
###### 

[2014-07-28T08:26:19+00:00] INFO: Starting Supervisor...
[2014-07-28T08:26:19+00:00] INFO: Supervisor pid: 8
[2014-07-28T08:26:19+00:00] INFO: Waiting for Supervisor to start...
[2014-07-28T08:26:20+00:00] INFO: Starting chef-client run...

Is this logs indicating correct operation/setup?

I can do "telnet <host> 80" and it connects, so it looks like apache server is running fine at port 80. I also see the new container instances show up as new nodes in Chef Server's portal, so that's good.

But from browser, going to "http://host:80" doesn't display any default apache page. I guess its because the apache2 cookbook doesn't have the apache home page by default?

Just want to validate this with you coz I haven't used apache2 cookbook before. If there is any other way for me to verify that container works correctly, please let me know. Thanks.

**Comment by tduffield** [comment]
The logs you showed indicate that chef-init started successfully and that it kicked off a chef-client run. The default recipe in the apache2 cookbook should give you a generic apache webpage. Your problem may be on the Docker side of things. If  you want to access port 80 running on the container you need to make sure that you expose that port. Did you expose port 80 on the container and bind it to a port running on the Docker host? Also be aware that if you are running in a VM (i.e. boot2docker) you will need to take that into consideration as well.

**Comment by snayakie** [comment]
Yes I was doing the port expose and map..... I think its working correctly, browser to that host:port goes to a page not found "/", that message is from apache. Going to a different port gives a browser error. I think the default apache welcome page just isn't put in by the apache2 cookbook.

**Comment by tduffield** [comment]
If you are getting a message from apache, then its working. I'm not sure what the default behavior of the apache2 cookbook is.
