### ISSUE TITLE
Not suitable to run chef-solo inside container

### ISSUE THREAD

**Issue by akranga** [chef-boneyard/chef-init#13]
This is a suggestion to extract provider/\* and resource/\* into HWRP cookbook so it could be reused by running chef-solo inside a container. If that is OK I can issue a PR

**Comment by tduffield** [comment]
It was an explicit design choice not to have the custom resources and providers in a cookbook. I do not see us extracting those libraries into a cookbook.

chef-init currently has a flow that supports running chef-client without a chef-server by running chef in local-mode (i.e. chef-zero). While chef-zero and chef-solo are essentially identical, if you want to run chef-solo inside of a container using the chef-init libraries my recommendation would be to add support for that flow to chef-init and knife-container rather then extracting resources and providers into a cookbook.
