### ISSUE TITLE
unable to get chef-init file

### ISSUE THREAD

**Issue by anandhas** [chef-boneyard/chef-init#14]
Hi,

I am creating a docker image with the help of knife container. In the Dockerfile we are using "chef-init --bootstrap", where in i am not able to find the chef-init file, i have installed chefdk, knife container etc, still not able to find this file. Let me know from where can i pick this file.

**Comment by tduffield** [comment]
The `chef-init` binary is part of the chef-container package. If you are using a base image that is provided be Chef (https://hub.docker.com/u/chef/), you do not need to worry about installing chef-container as it comes pre-installed. Knife-container will assume that your base image already has chef-container installed. To install chef-container, you just need to add the following line to your Dockerfile:

```
RUN curl -L https://getchef.com/chef/install.sh | bash -s -- -P container 
```

**Comment by anandhas** [comment]
Thanks Tom. I was assuming chef-init is an individual executable which would be place along with other executables of chef. My sample knife container work went thru fine. Thanks.
