### ISSUE TITLE
chef-init doesn't adopt orphaned child

### ISSUE THREAD

**Issue by ghost** [chef-boneyard/chef-init#16]
In the actual state (build or run), if a daemon process is killed, it becomes zombie.
In my case, chef-client wait forever the restart of a daemon process (waiting the disparition of the old PID)

As init (PID 1) replacement, chef-init should manage the termination of daemon process.

I have translated a function from https://github.com/phusion/baseimage-docker/blob/master/image/bin/my_init (python) into chef-init (https://github.com/Da-Wei/chef-init/tree/nozombie). 
I don't know if I can do a pull request (Opscode Individual Contributor License Agreement, paragraph 6).

**Comment by tduffield** [comment]
Go ahead and submit the pull request. You'll just need to sign the CLA before we can merge the code. I'll take a deeper look into the code tomorrow morning.

**Comment by tduffield** [comment]
Closed by #17
