### ISSUE TITLE
Does chef-init run the recipes on every container run?

### ISSUE THREAD

**Issue by snayakie** [chef-boneyard/chef-init#26]
It appears that on every container run, the recipes are run every time. i.e., 'chef-init --onboot' is doing that I think.

Is there any way to avoid this? i.e., so that the recipes are installed only at 'knife container docker build' , and on running containers we don't run the whole recipes but just start the services that are specified in first-boot.json ?

**Comment by tduffield** [comment]
At the moment, no. That is a feature that is being discussed for a future version.

**Comment by snayakie** [comment]
In the 'knife container docker init' generated Dockerfile, if I change ENTRYPOINT to be something other than 'chef-init' ....... is there any runit command I can run, which will just start 'all services' ?

**Comment by tduffield** [comment]
runsvdir -P /opt/chef/service - that is what chef-init runs

**Comment by snayakie** [comment]
ok, will try that, thanks.
Following up on nsenter, I tried to stop/start my process from nsenter shell, but it doesn't work, hangs. Is this expected behaviour from nsenter?

**Comment by tduffield** [comment]
No.

**Comment by snayakie** [comment]
ok, I couldn't kill any processes from nsenter (docker-enter) either. So was wondering if chef-container had anything to do with it.

**Comment by tduffield** [comment]
Nope.

**Comment by snayakie** [comment]
ok
