### ISSUE TITLE
chef-init --bootstrap vs --onboot

### ISSUE THREAD

**Issue by snayakie** [chef-boneyard/chef-init#27]
Can you give some insight on the difference between the --bootstrap (run during image build) and --onboot , as to which parts of the recipes does it run for each of these CLI options? I see that it does different things during image build (--bootstrap) and during start of container (--onboot).

**Comment by tduffield** [comment]
There is no difference in what parts of the recipes either run. The only difference between the two is that --bootstrap exits when the chef-client run finishes and --onboot stays alive

**Comment by snayakie** [comment]
Ok. Regarding the recipe, if there is a fragment like this:

execute "start tnpfa" do
  command "service tnpfa start"
end

This doesn't work , appears to hang. Similar to how it was in nsenter. But a statement like this works:

service 'tnpfa' do
  action [:start, :enable]
end

So the "service" statement (latter) internally invokes "sv", is it?

Will the "execute" (former) way to start/stop services not work in the chef-container?

**Comment by tduffield** [comment]
No it will not.

**Comment by snayakie** [comment]
So using "service ... action :start " statement uses the runit / sv basically .

**Comment by tduffield** [comment]
Correct: 
https://github.com/opscode/chef-init/blob/master/lib/chef/resource/container_service.rb#L33
https://github.com/opscode/chef-init/blob/master/lib%2Fchef%2Fprovider%2Fcontainer_service%2Frunit.rb
